name: math_app_for_kid
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  rive: ^0.6.8
  flutter_spinkit: ^5.0.0 # Loading indicator
  dio: ^3.0.10 # Http client for call API
  shared_preferences: ^2.0.4 # Local Storage
  flutter_screenutil: ^4.0.3+3 # Adapting screen and font size
  provider: ^5.0.0 # State management
  npreferences: ^3.0.0+1
  yaml: ^3.1.0
  image: ^3.0.1
  xml: ^5.0.2
  flutter_native_splash: ^1.1.4+1

dev_dependencies:
  build_runner: any
  flutter_test:
    sdk: flutter
  lint: any # Setup lint for Dart/Flutter
  test: any
  flutter_launcher_icons: any # Generate launcher icons
  fluttertoast: ^7.1.8
  meta: ^1.3.0
  logger: ^0.9.4
  pedantic: ^1.11.0

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/base/icons/app_icon_ios.png"
  image_path_android: "assets/base/icons/app_icon_ad.png"
  adaptive_icon_background: "assets/base/icons/adaptive_icon_background.png"
  adaptive_icon_foreground: "assets/base/icons/adaptive_icon_foreground.png"

flutter_native_splash:
  image: "assets/base/splash/splash_image.png"
  color: "#95C4FC"
  android_disable_fullscreen: true

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/base/icons/
    - assets/base/character/
    - assets/base/images/lesson/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
